### ISSUE TITLE
ttl type inconsistent

### ISSUE THREAD

**Issue by venkatramanm** [beckn/protocol-specifications#343]
---

Name: Protocol Specifications
Title: "ttl type inconsistent"
Labels: C4GT Community

---

## Description

ttl in provider object is of type integer where every where else it is of type Duration ( ISO8601 format) Need to fix for consistency.

## Goals

- Check and maintain consistency

## Expected Outcome

- Check and maintain consistency

## Implementation Details
- Update Provider TTL to Duration

---

### Project

Beckn

### Organization Name:

Beckn Open Collective

### Domain

Others

### Tech Skills Needed:

Open API 3.0
Github actions

### Mentor(s)

Ravi Prakash

### Complexity

Low

### Category

Bug

### Sub Category

Reproducible

**Comment by emmayank** [comment]
@ravi-prakash-v ttl is used at 6 places in the Core Specs ( Transaction.yaml). should we change all as '#/components/schemas/Duration'

1. Catalogue
```
ttl:
          description: Duration in seconds after which this catalog will expire
          type: string
```
2. Category
```
ttl:
          description: Time to live for an instance of this schema
```
3. Context
```
ttl:
          description: The duration in ISO8601 format after timestamp for which this message holds valid
          type: string
```
4. Item
```
ttl:
          description: Time to live in seconds for an instance of this schema
          type: string
```
5. Provider
```
ttl:
          description: 'The time-to-live in seconds, for this object. This can be overriden at deeper levels. A value of -1 indicates that this object is not cacheable.'
          type: integer
          minimum: -1
```
6. Quotation
```
ttl:
          $ref: '#/components/schemas/Duration'
```
